package models;

import java.math.BigDecimal;
import java.sql.Timestamp;

public class score {
    private int idScore;       // if your table has id_score (history version)
    private int idUser;
    private int idSkill;
    private BigDecimal score;
    private Timestamp createdAt;

    public score() {}

    // For inserting (no idScore, createdAt generated by DB)
    public score(int idUser, int idSkill, BigDecimal score) {
        this.idUser = idUser;
        this.idSkill = idSkill;
        this.score = score;
    }

    // For reading full row
    public score(int idScore, int idUser, int idSkill, BigDecimal score, Timestamp createdAt) {
        this.idScore = idScore;
        this.idUser = idUser;
        this.idSkill = idSkill;
        this.score = score;
        this.createdAt = createdAt;
    }

    public int getIdScore() {
        return idScore;
    }

    public void setIdScore(int idScore) {
        this.idScore = idScore;
    }

    public int getIdUser() {
        return idUser;
    }

    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }

    public int getIdSkill() {
        return idSkill;
    }

    public void setIdSkill(int idSkill) {
        this.idSkill = idSkill;
    }

    public BigDecimal getScore() {
        return score;
    }

    public void setScore(BigDecimal score) {
        this.score = score;
    }

    public Timestamp getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }
}
